// <auto-generated />
using FinDashboard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinDashboard.API.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20241128102814_Creating Auth Database")]
    partial class CreatingAuthDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "7b4a7311-2735-4a8f-b173-dfd5a1e8349f",
                            ConcurrencyStamp = "7b4a7311-2735-4a8f-b173-dfd5a1e8349f",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "876bf57e-6adf-45ff-b453-8ca9b9054b93",
                            ConcurrencyStamp = "876bf57e-6adf-45ff-b453-8ca9b9054b93",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
